# Generated by Django 6.0.1 on 2026-02-04 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_product_productcolor'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='productStatus',
            field=models.BooleanField(default=True),
        ),
    ]
